apiVersion: v1
kind: ConfigMap
metadata:
  name: virtio-dp-config
  namespace: kube-system
data:
  config.json: |
    {
      "resourceNamePrefix": "virtio",
      "resourcePrefix": "openshift.io",
      "socketUser": "openvswitch",
      "resourceList": [
        {
          "resourceName": "vhost-phy0",
          "numDevices": 100,
          "baseDir": "/var/run/virtio-dp/vhost-user/",
          "topologyHintsFrom": [
            {
              "pciAddress": "0000:ab:cd.0"
            }
          ]
        }
      ]
    }
